/**
 * Route constants for Router.
 */
/**
 * Route of page for the ResponsiveLayout.
 */
export const RESPONSIVE_ROUTE: string = 'pages/ResponsiveIndex';

/**
 * Route of page for the AdaptiveLayout.
 */
export const ADAPTIVE_ROUTE: string = 'pages/AdaptiveIndex';

/**
 * Route of page for the SystemCapabilities.
 */
export const SYSTEM_CAPABILITIES_ROUTE: string = 'pages/SystemCapabilitiesIndex';